In [1]:
import numpy as np

In [2]:
X = np.array([
    [1, 2, 3, 4],
    [5, 5, 6, 7],
    [1, 4, 2, 3],
    [5, 3, 2, 1], 
    [8, 1, 2, 2]
])
X

array([[1, 2, 3, 4],
       [5, 5, 6, 7],
       [1, 4, 2, 3],
       [5, 3, 2, 1],
       [8, 1, 2, 2]])

In [3]:
# scaling the original dataset before PCA
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-1.11803399, -0.70710678,  0.        ,  0.29138576],
       [ 0.372678  ,  1.41421356,  1.93649167,  1.74831455],
       [-1.11803399,  0.70710678, -0.64549722, -0.19425717],
       [ 0.372678  ,  0.        , -0.64549722, -1.16554303],
       [ 1.49071198, -1.41421356, -0.64549722, -0.6799001 ]])

In [4]:
class PCA():
    def __init__(self, n_components = None):
        self.n_components = n_components
    
    def fit_transform(self, A):
        self.A_central = A - np.mean(A, axis=0)
        cov_mat = np.dot(self.A_central.T, self.A_central)
        eigenvalues, eigenvectors =  np.linalg.eig(cov_mat)
        sorted_index = np.argsort(eigenvalues)[::-1]
        
        if self.n_components == None:
            self.vectors = eigenvectors[:, sorted_index]
        elif self.n_components > min(A.shape[0], A.shape[1]):
            print('Error: n_components must be smaller than min of shape of design matrix!')
        else:
            self.vectors = eigenvectors[:, sorted_index][0:self.n_components]
        return np.dot(self.A_central, self.vectors.T)

In [5]:
pca = PCA(n_components=2)
pca.fit_transform(X)

array([[-1.4611346 ,  1.12036836],
       [-1.49743732, -3.98124212],
       [-2.61943625,  1.8455649 ],
       [ 1.11098979,  0.93845399],
       [ 4.46701838,  0.07685486]])